{% set name = "pyiron_contrib" %}
{% set version = "0.1.18" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_contrib-{{ version }}.tar.gz
  sha256: 3cb2262858455d4b26b04c7e64feb46fcbaa7990d67cc95fbcb8e64233fa2786

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pyiron_snippets >=0.1.3
    - python >={{ python_min }}
    - matplotlib-base >=3.9.1
    - numpy >=1.26.4  # for numba compatibility
    - pyiron_base >=0.9.11
    - scipy >=1.13.0
    - seaborn >=0.13.2
    - pyparsing >=3.1.2

test:
  imports:
    - pyiron_contrib
  commands:
    - pip check
  requires:
    - pip
    - boto3
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_contrib
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
