{% set name = "pyiron_contrib" %}
{% set version = "0.1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_contrib-{{ version }}.tar.gz
  sha256: 32e0ca45cba2f7f5b0c576130f6664c45f89278189205c202aa29d2e095c28a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - pyiron_snippets >=0.1.1
    - python >=3.6
    - matplotlib-base >=3.8.3
    - numpy >=1.26.4  # for numba compatibility
    - pyiron_base >=0.9.0
    - scipy >=1.12.0
    - seaborn >=0.13.2
    - pyparsing >=3.1.2

test:
  imports:
    - pyiron_contrib
  commands:
    - pip check
  requires:
    - pip
    - boto3

about:
  home: https://github.com/pyiron/pyiron_contrib
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
